version: 2
updates:
- package-ecosystem: Yarn
  directory: "/"
  schedule:
    interval: daily
    time: "08:00"
    timezone: "America/Los_Angeles"
  versioning-strategy: lockfile-only
  labels:
  - "dependencies"
